[package]
name = "mws-tests"
version = "0.1.0"
authors = ["Flux Xu <fluxxu@gmail.com>"]

[dependencies]
mws = { path = "../mws" }
mws-derive = { path = "../mws-derive" }
chrono = { version = "0.4", features = ["serde"] }
